In [7]:
# %load tensorgen.py
from scipy import misc
import numpy as np
import os

# Get the maximum X/Y dimension for each image in this folder
def getMaxWidthHeight(fileName):
    imagearr = misc.imread(fileName)
    return imagearr.shape[0], imagearr.shape[1]

In [8]:
# read image pixels array
def populateImageTensor(fileName,imgNumber,tensorArray,w,h):
    imagearr = misc.imread(fileName)
    #normalizing the pixel values to be in the range of 0 to 1
    imagearr = imagearr/255.0
    imageWidth = imagearr.shape[0]
    imageHeight = imagearr.shape[1]
    #create a view of the tensor - a pointer to the 3d array within the 4d array.
    tensorView = tensorArr[imgNumber,:,0:imageWidth,0:imageHeight]
    imagearr = np.reshape(imagearr,(3,imageWidth,imageHeight))
    np.copyto(tensorView,imagearr)

In [9]:
# get path for images
currentPath = os.path.abspath(os.curdir)
filenames = next(os.walk(currentPath))[2]

imgCount = 0
processFiles = []
listofX = []
listofY = []

for file in filenames:
    fileName, fileExtension = os.path.splitext(file)
    if fileExtension == ".png":
        imgCount = imgCount + 1
        processFiles.append(file)
        x,y = getMaxWidthHeight(file)
        # get the max width, height
        listofX.append(x)
        listofY.append(y)

X = max(listofX)
Y = max(listofY)

# create 4-d array tensor
tensorArr = np.ndarray(shape=(10,3,X,Y),dtype='float64')
tensorArr.fill(-1)

i = 0
for file in processFiles:
    populateImageTensor(file,i,tensorArr, X, Y)
    i = i + 1

In [3]:
tensorArr[2,0]

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ..., 
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [98]:
imagearr = misc.imread('triangle_5.png')
imagearr = imagearr/255.0
imgNumber = 0
imageWidth = imagearr.shape[0]
imageHeight = imagearr.shape[1]
tensorView = tensorArr[imgNumber,:,0:imageWidth,0:imageHeight]
imagearr = np.reshape(imagearr,(3,imageWidth,imageHeight))
np.copyto(tensorView,imagearr)

In [75]:
tarr = misc.imread('triangle_5.png')
from IPython.core.display import Image 
Image('triangle_5.png') 

x = np.ndarray(shape=(1,1,3))
x.fill(1)
x[:,0,0].fill(0)
x

array([[[ 0.,  1.,  1.]]])

In [76]:
np.reshape(x,(3,1,1))

array([[[ 0.]],

       [[ 1.]],

       [[ 1.]]])

In [30]:
b

array([[ 5.],
       [ 5.]])

In [32]:
aview = a[0,0:2,0:1]

In [33]:
aview

array([[ 0.],
       [ 0.]])

In [34]:
np.copyto(aview,b)

In [35]:
a

array([[[ 5.,  0.,  0.,  0.],
        [ 5.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])